[project]
name = "cvgeomkit"
version = "0.1.3"
description = "Geometry-based image analysis toolkit"
readme = "README.md"
authors = [
    { name = "polymorvic", email = "polymorphic.bite@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "pillow>=12.2.0",
    "pyyaml>=6.0.3",
    "shapely>=2.1.2",
]

[project.scripts]
cvgeomkit = "cvgeomkit:main"

[build-system]
requires = ["uv_build>=0.8.2,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyterlab>=4.5.7",
    "ruff>=0.15.12",
]
